### ISSUE TITLE
Prediction showing only current balance

### ISSUE THREAD

**Issue by esiebomaj** [Aasess/ExpenseTracker#6]
I ran the app locally and i discovered that in the analysis tab the prediction just shows the current balance

**Comment by Aasess** [comment]
Thanks for responding. Could you be more specific? Did you put enough data
for training the model?

**Comment by Aasess** [comment]
well, I re-checked my code and run the server again with more data entry and it worked for me. I couldn't find any issue over there. One thing I haven't mentioned is that , in settings.py I have used my timezone(Kathmandu), replace it with your timezone...
